/**
 * The icons the app uses (lucide), by sprite id. public/icons.svg holds one
 * <symbol> per entry (npm run sprites); <Icon name="…"> draws it with <use>,
 * so each page carries a short reference instead of the paths.
 */
export const ICONS = {
  activity: "Activity",
  "arrow-down": "ArrowDown",
  "arrow-left": "ArrowLeft",
  "arrow-right": "ArrowRight",
  "arrow-up-down": "ArrowUpDown",
  check: "Check",
  "check-circle": "CheckCircle2",
  "chevron-down": "ChevronDown",
  compass: "Compass",
  contrast: "Contrast",
  crop: "Crop",
  download: "Download",
  ellipsis: "Ellipsis",
  // lucide names this one by its axis: its triangles face left and right, a mirror left to right.
  "flip-horizontal-2": "FlipVertical2",
  heart: "Heart",
  info: "Info",
  layers: "Layers",
  pencil: "Pencil",
  leaf: "Leaf",
  "link-2": "Link2",
  loader: "Loader2",
  lock: "Lock",
  mail: "Mail",
  "message-square": "MessageSquare",
  minus: "Minus",
  plus: "Plus",
  "refresh-cw": "RefreshCw",
  repeat: "Repeat",
  "rotate-ccw": "RotateCcw",
  "rotate-cw": "RotateCw",
  ruler: "Ruler",
  search: "Search",
  send: "Send",
  "sliders-horizontal": "SlidersHorizontal",
  "share-2": "Share2",
  "shopping-bag": "ShoppingBag",
  sparkles: "Sparkles",
  sun: "Sun",
  "trash-2": "Trash2",
  truck: "Truck",
  user: "User",
  "undo-2": "Undo2",
  "wand-sparkles": "WandSparkles",
  x: "X",
  "zoom-in": "ZoomIn",
} as const;

export type IconName = keyof typeof ICONS;
